# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

workflows:
  test:
    jobs:
      - test:
          version: '15.1'
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node



jobs:
  test:
    docker:
      - image: circleci/node:11.15.0
    steps:
      - checkout
      - run: npm install
      - run: mkdir ~/results
      - run:
          command: npm test
          when: always
      - store_test_results:
          path: ~/results
      - store_artifacts:
          path: ~/results

                
